Consoller/Controllers/GICsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Consoller.Areas.Auth.Models;
using Consoller.Models;

namespace Consoller.Controllers
{
    public class GICsController : Controller
    {
        private dbcontext db = new dbcontext();
        public static string img = "",thm="",ca="";
        // GET: GICs
        public async Task<ActionResult> Index()
        {
            return View(await db.Gic.ToListAsync());
        }

        // GET: GICs/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GIC gIC = await db.Gic.FindAsync(id);
            if (gIC == null)
            {
                return HttpNotFound();
            }
            return View(gIC);
        }

        // GET: GICs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GICs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Gid,Date,ApplicationNo,AccountNo,BankName,Amount,Status,Fundstatus,CreatedBy")] GIC gIC)
        {
            if (ModelState.IsValid)
            {
                db.Gic.Add(gIC);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(gIC);
        }

        // GET: GICs/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GIC gIC = await db.Gic.FindAsync(id);
            img = gIC.Files;
            thm = gIC.Certificate;
            ca = gIC.Caq;
            if (gIC == null)
            {
                return HttpNotFound();
            }
            return View(gIC);
        }

        // POST: GICs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Gid,Date,ApplicationNo,AccountNo,BankName,Amount,Status,Fundstatus,CreatedBy,Files,Certificate,Username,Password,SecurityQuestion,Answer,Caq,CaqUser,CaqPassword,EmailId,EmailPassword,ArrimaUser,ArrimaPassword")] GIC gIC, HttpPostedFileBase file, HttpPostedFileBase thumb, HttpPostedFileBase Caq,Helper help)
        {
            if (ModelState.IsValid)
            {
                using (var transaction = db.Database.BeginTransaction())
                {
                    try
                    {
                        if (file==null || thumb==null || Caq==null)
                        {

                            gIC.Files = file != null ? help.uploadfile(file) : img;
                            gIC.Certificate = thumb != null ? help.uploadfile(thumb) : img;
                            gIC.Caq = Caq != null ? help.uploadfile(Caq) : ca;
                            db.Entry(gIC).State = EntityState.Modified;
                            await db.SaveChangesAsync();
                            Application app = db.Applications.FirstOrDefault(x => x.ApplicationNo == gIC.ApplicationNo);
                            TempData["Success"] = "Gic Account Updated Successfully";
                            transaction.Commit();
                            return RedirectToAction("Create", "Application", new { id = app.InquiryId });
                        }
                        else if(file.ContentType == "application/pdf")
                        {
                            gIC.Files = file != null ? help.uploadfile(file) : img;
                            gIC.Certificate = thumb != null ? help.uploadfile(thumb) : img;
                            gIC.Caq = Caq != null ? help.uploadfile(Caq) : ca;
                            db.Entry(gIC).State = EntityState.Modified;
                            await db.SaveChangesAsync();
                            Application app = db.Applications.FirstOrDefault(x => x.ApplicationNo == gIC.ApplicationNo);
                            TempData["Success"] = "Gic Account Updated Successfully";
                            transaction.Commit();
                            return RedirectToAction("Create", "Application", new { id = app.InquiryId });
                        }
                        else
                        {
                            TempData["danger"] = "upload only pdf file";
                            transaction.Commit();
                            return RedirectToAction("Edit", "Gics", new { id = gIC.Gid });
                        }
                    }
                    catch (Exception)
                    {
                        transaction.Rollback();
                        Application app = db.Applications.FirstOrDefault(x => x.ApplicationNo == gIC.ApplicationNo);
                        TempData["danger"] = "Sorry Gic Update Failed";
                        return RedirectToAction("Create", "Application", new { id = app.InquiryId });
                        throw;
                    } 
                }
            }
            return View(gIC);
        }

        // GET: GICs/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GIC gIC = await db.Gic.FindAsync(id);
            if (gIC == null)
            {
                return HttpNotFound();
            }
            return View(gIC);
        }

        // POST: GICs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            GIC gIC = await db.Gic.FindAsync(id);
            db.Gic.Remove(gIC);
            await db.SaveChangesAsync();
            return RedirectToAction("Dashboard", "Processing", new { id = gIC.ApplicationNo });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Consoller/Views/GICs/Create.cshtml
@model Consoller.Areas.Auth.Models.GIC

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Process.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>GIC</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicationNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicationNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccountNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccountNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BankName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BankName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BankName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fundstatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fundstatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fundstatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Consoller/Views/GICs/Delete.cshtml
@model Consoller.Areas.Auth.Models.GIC

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Process.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GIC</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccountNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BankName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fundstatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fundstatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Consoller/Views/GICs/Details.cshtml
@model Consoller.Areas.Auth.Models.GIC

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/main.cshtml";
}

<h2>Details</h2>

<div class="card">
    <div class="card-body">
        <h4>GIC</h4>
        <hr />
        <table class="table table-nowrap mb-0">
            <tbody>
                <tr>
                    <th scope="row">@Html.DisplayNameFor(model => model.Date)</th>
                    <td> @Html.DisplayFor(model => model.Date)</td>

                </tr>
                @*<tr>
                        <th scope="row">@Html.DisplayNameFor(model => model.Applied)</th>
                        <td>
                            @if (Model.Applied == null)
                            {
                                <a href="@Url.Action("Edit","Offerletters",new { id=Model.Lid})">Click Here Update Applied Date</a>
                            }
                            else
                            {
                                @Html.DisplayFor(model => model.Applied)
                            }

                        </td>

                    </tr>
                    <tr>
                        <th scope="row">@Html.DisplayNameFor(model => model.Received)</th>
                        <td>
                            @if (Model.Received == null)
                            {
                                <a href="@Url.Action("Edit","Offerletters",new { id=Model.Lid})" class="badge badge-danger">Click Here Update Received Date</a>
                            }
                            else
                            {
                                @Html.DisplayFor(model => model.Received)
                            }
                        </td>

                    </tr>*@
                <tr>
                    <th scope="row">Account</th>
                    <td> @Html.DisplayNameFor(model => model.AccountNo)</td>

                </tr>
                <tr>
                    <th scope="row">Bank Name</th>
                    <td> @Html.DisplayFor(model => model.BankName)</td>

                </tr>
                <tr>
                    <th scope="row">Amount</th>
                    <td>@Html.DisplayFor(model => model.Amount)</td>

                </tr>
                <tr>
                    <th scope="row">Created By</th>
                    <td> @Html.DisplayFor(model => model.CreatedBy)</td>

                </tr>
                <tr>
                    <th scope="row">TT</th>
                    @if (Model.Files != null)
                    {
                        <td> <a href="~/Uploadfile/@Model.Files"><i class="far fa-file-pdf" style="font-size: 30px;"></i></a></td>
                    }
                    else
                    {
                        <td>File Not Found</td>
                    }

                </tr>
                <tr>
                    <th scope="row">Certificate</th>
                    @if (Model.Certificate != null)
                    {
                        <td><a href="~/Uploadfile/@Model.Certificate"><i class="far fa-file-pdf" style="font-size: 30px;"></i></a></td>

                    }
                    else
                    {
                        <td>File Not Found</td>

                    }

                </tr>
                <tr>
                    <th scope="row">Caq</th>
                    @if (Model.Caq != null)
                    {
                        <td> <a href="~/Uploadfile/@Model.Caq"><i class="far fa-file-pdf" style="font-size: 30px;"></i></a></td>

                    }
                    else
                    {
                        <td>File Not Found</td>
                    }


                </tr>
                <tr>
                    <th scope="row">User Name</th>
                    <td> @Html.DisplayFor(model => model.UserName)</td>

                </tr>
                <tr>
                    <th scope="row">Password</th>
                    <td> @Html.DisplayFor(model => model.Password)</td>

                </tr>
                <tr>
                    <th scope="row">Question</th>
                    <td> @Html.DisplayFor(model => model.SecurityQuestion)</td>

                </tr>
                <tr>
                    <th scope="row">Password</th>
                    <td> @Html.DisplayFor(model => model.Password)</td>

                </tr>
            </tbody>
        </table>

        <p>
            @Html.ActionLink("Back to List", "Create", "Application", new { id = Model.ApplicationNo })
        </p>

    </div>
</div>

Consoller/Views/GICs/Edit.cshtml
@model Consoller.Areas.Auth.Models.GIC

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/main.cshtml";
}


<div class="card">
    <div class="card-body">
      @using (Html.BeginForm("Edit", "GICs", FormMethod.Post, new { enctype = "multipart/form-data" }))
      {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>GIC</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Gid)
                @Html.HiddenFor(model => model.CreatedBy)
                @Html.HiddenFor(model => model.ApplicationNo)
                <div class="form-group">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.AccountNo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AccountNo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AccountNo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.BankName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.BankName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.BankName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                    </div>
                </div>

               

                <div class="form-group">
                    @Html.LabelFor(model => model.Fundstatus, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Fundstatus, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Fundstatus, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Files, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input id="file" type="file" title="search image" class="form-control" name="file" />
                        <small class="text-danger">Upload only pdf file</small>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Certificate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input id="thumb" type="file" title="search image" class="form-control" name="thumb" />
                        <small class="text-danger">Upload only pdf file</small>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Caq, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input id="caq" type="file" title="search image" class="form-control" name="caq" />
                        <small class="text-danger">Upload Caq only for Quebec</small> | <small class="text-danger">Upload only pdf file</small>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.CaqUser, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CaqUser, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CaqUser, "", new { @class = "text-danger" })
                    </div>
                </div>
                 <div class="form-group">
                    @Html.LabelFor(model => model.CaqPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CaqPassword, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CaqPassword, "", new { @class = "text-danger" })
                    </div>
                </div> 
                <div class="form-group">
                    @Html.LabelFor(model => model.ArrimaUser, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ArrimaUser, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ArrimaUser, "", new { @class = "text-danger" })
                    </div>
                </div> 
                <div class="form-group">
                    @Html.LabelFor(model => model.ArrimaPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ArrimaPassword, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ArrimaPassword, "", new { @class = "text-danger" })
                    </div>
                </div> 
                <div class="form-group">
                    <label class="col-md-2">Gic Username</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2">Gic Password</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
               
               
                <div class="form-group">
                    @Html.LabelFor(model => model.SecurityQuestion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SecurityQuestion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SecurityQuestion, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Answer, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Answer, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Answer, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.EmailId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.EmailId, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.EmailPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.EmailPassword, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.EmailPassword, "", new { @class = "text-danger" })
                    </div>
                </div>
              
                @if (Model.Files != null || Model.Certificate != null)
                {
                    <div class="form-group">
                        @if (Model.Files != null)
                        {
                            <a href="~/Uploadfile/@Model.Files" target="_blank">TT Recipt</a>
                        }
                        @if (Model.Certificate != "False")
                        {
                            <span> | </span>  <a href="~/Uploadfile/@Model.Certificate" target="_blank">Gic Certificate</a>
                        }
                        @if (Model.Caq != "False")
                        {
                            <span> | </span>  <a href="~/Uploadfile/@Model.Caq" target="_blank">Caq</a>
                        }
                    </div>
                }

                <div class="form-group">
                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Status)
                            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>

Consoller/Views/GICs/Index.cshtml
@model IEnumerable<Consoller.Areas.Auth.Models.GIC>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Process.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AccountNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BankName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fundstatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApplicationNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AccountNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BankName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Amount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fundstatus)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedBy)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Gid }) |
            @Html.ActionLink("Details", "Details", new { id=item.Gid }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Gid })
        </td>
    </tr>
}

</table>