Consoller/Controllers/MedicalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Consoller.Areas.Auth.Models;
using Consoller.Models;

namespace Consoller.Controllers
{
    public class MedicalsController : Controller
    {
        private dbcontext db = new dbcontext();
        public static string img = "";
        // GET: Medicals
        public async Task<ActionResult> Index()
        {
            return View(await db.Medicals.ToListAsync());
        }

        // GET: Medicals/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicals medicals = await db.Medicals.FindAsync(id);
            if (medicals == null)
            {
                return HttpNotFound();
            }
            return View(medicals);
        }

        // GET: Medicals/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Medicals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Mid,ApplicationNo,Date,HospitalName,BookedBy,Note")] Medicals medicals)
        {
            if (ModelState.IsValid)
            {
                db.Medicals.Add(medicals);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(medicals);
        }

        // GET: Medicals/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicals medicals = await db.Medicals.FindAsync(id);
            img = medicals.Files;
            if (medicals == null)
            {
                return HttpNotFound();
            }
            return View(medicals);
        }

        // POST: Medicals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Mid,ApplicationNo,Date,HospitalName,BookedBy,Note,Files")] Medicals medicals, HttpPostedFileBase file, Helper help)
        {
            if (ModelState.IsValid)
            {
                medicals.Files = file != null ? help.uploadfile(file):img;
                db.Entry(medicals).State = EntityState.Modified;
                await db.SaveChangesAsync();
                TempData["Success"] = "Medical Updated Successfully";
                return RedirectToAction("Dashboard", "Processing", new { id = medicals.ApplicationNo });
            }
            return View(medicals);
        }

        // GET: Medicals/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicals medicals = await db.Medicals.FindAsync(id);
            if (medicals == null)
            {
                return HttpNotFound();
            }
            return View(medicals);
        }

        // POST: Medicals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Medicals medicals = await db.Medicals.FindAsync(id);
            db.Medicals.Remove(medicals);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Consoller/Views/Medicals/Create.cshtml
@model Consoller.Areas.Auth.Models.Medicals

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Process.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Medicals</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicationNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicationNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HospitalName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HospitalName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HospitalName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Consoller/Views/Medicals/Delete.cshtml
@model Consoller.Areas.Auth.Models.Medicals

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Process.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Medicals</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HospitalName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HospitalName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BookedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Consoller/Views/Medicals/Details.cshtml
@model Consoller.Areas.Auth.Models.Medicals

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Process.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Medicals</h4>
    <hr />
    <table class="table table-nowrap mb-0">
        <tbody>
            <tr>
                <th scope="row">@Html.DisplayNameFor(model => model.Date)</th>
                <td> @Html.DisplayFor(model => model.Date)</td>

            </tr>
            @*<tr>
                    <th scope="row">@Html.DisplayNameFor(model => model.Applied)</th>
                    <td>
                        @if (Model.Applied == null)
                        {
                            <a href="@Url.Action("Edit","Offerletters",new { id=Model.Lid})">Click Here Update Applied Date</a>
                        }
                        else
                        {
                            @Html.DisplayFor(model => model.Applied)
                        }

                    </td>

                </tr>
                <tr>
                    <th scope="row">@Html.DisplayNameFor(model => model.Received)</th>
                    <td>
                        @if (Model.Received == null)
                        {
                            <a href="@Url.Action("Edit","Offerletters",new { id=Model.Lid})" class="badge badge-danger">Click Here Update Received Date</a>
                        }
                        else
                        {
                            @Html.DisplayFor(model => model.Received)
                        }
                    </td>

                </tr>*@
            <tr>
                <th scope="row">Hospital Name</th>
                <td> @Html.DisplayFor(model => model.HospitalName)</td>

            </tr>
            <tr>
                <th scope="row">Note</th>
                <td> @Html.DisplayFor(model => model.Note)</td>

            </tr>
            <tr>
                <th scope="row">Medical</th>
                @if (Model.Files != null)
                {
                    <td> <a href="~/Uploadfile/@Model.Files"><i class="far fa-file-pdf" style="font-size: 30px;"></i></a></td>
                }
                else
                {
                    <td>File Not Found</td>
                }

            </tr>
            
        </tbody>
    </table>

    
</div>
<p>
    @Html.ActionLink("Back to List", "Create", "Application", new { id = Model.ApplicationNo })
</p>

Consoller/Views/Medicals/Edit.cshtml
@model Consoller.Areas.Auth.Models.Medicals

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/main.cshtml";
}


<div class="card">
    <div class="card-body">
       @using (Html.BeginForm("Edit", "Medicals", FormMethod.Post, new { enctype = "multipart/form-data" }))
       {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Medicals</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Mid)
                @Html.HiddenFor(model => model.ApplicationNo)
               @Html.HiddenFor(model => model.BookedBy)

                <div class="form-group">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.HospitalName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.HospitalName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.HospitalName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.BookedBy, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.BookedBy, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.BookedBy, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Files, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input id="file" type="file" title="search image" class="form-control" name="file" />
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
                    </div>
                </div>
                @if (Model.Files != null)
                {
                    <div class="form-group">
                        @if (Model.Files != "False")
                        {
                            <a href="~/Uploadfile/@Model.Files" target="_blank">Medical</a>
                        }
                        
                    </div>
                }
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Update" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Create","Application",new { id=Model.ApplicationNo})
        </div>

</div>
</div>

Consoller/Views/Medicals/Index.cshtml
@model IEnumerable<Consoller.Areas.Auth.Models.Medicals>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Process.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HospitalName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BookedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Note)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ApplicationNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HospitalName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BookedBy)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Note)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Mid }) |
            @Html.ActionLink("Details", "Details", new { id=item.Mid }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Mid })
        </td>
    </tr>
}

</table>

Consoller/Views/Medicals/Partial_Medical.cshtml
@model IEnumerable<Consoller.Areas.Auth.Models.Medicals>
@using Consoller.Areas.Auth.Models
@{ 
    dbcontext db = new dbcontext();
}


        <table class="table">
            <tr>

                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HospitalName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BookedBy)
                </th>

                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HospitalName)
                    </td>
                    <td>
                        @db.tblreceptionists.FirstOrDefault(x=>x.rid==item.BookedBy).name
                    </td>

                    <td>
                        <a href="@Url.Action("Edit","Medicals",new {id=item.Mid })" class="badge badge-primary">Edit</a> |
                        <a href="@Url.Action("Delete","Medicals",new {id=item.Mid })" class="badge badge-danger">Delete</a>
                        @Html.ActionLink("Preview", "Details", "Medicals", new { id = item.Mid }, new { @class = " badge badge-warning" }) |

                    </td>
                </tr>
            }

        </table>